'use client';

import { motion } from 'framer-motion';
import { Brain, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface AIExplanationProps {
  explanation: string;
  decision: 'APPROVE' | 'HOLD' | 'BLOCK';
}

export default function AIExplanation({ explanation, decision }: AIExplanationProps) {
  const getDecisionIcon = () => {
    switch (decision) {
      case 'APPROVE':
        return <CheckCircle2 className="w-6 h-6 text-success" />;
      case 'HOLD':
        return <AlertTriangle className="w-6 h-6 text-warning" />;
      case 'BLOCK':
        return <AlertTriangle className="w-6 h-6 text-danger" />;
    }
  };

  const getDecisionBg = () => {
    switch (decision) {
      case 'APPROVE':
        return 'bg-success-light/30 border-success/30';
      case 'HOLD':
        return 'bg-warning-light/30 border-warning/30';
      case 'BLOCK':
        return 'bg-danger-light/30 border-danger/30';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`rounded-xl p-6 border-2 ${getDecisionBg()}`}
    >
      <div className="flex items-center gap-3 mb-4">
        <div className="p-2 bg-white rounded-lg shadow-sm">
          <Brain className="w-6 h-6 text-primary-600" />
        </div>
        <div>
          <h3 className="font-bold text-slate-800">AI Analysis</h3>
          <p className="text-sm text-slate-500">Generated by Invoice Physics Engine</p>
        </div>
        <div className="ml-auto">
          {getDecisionIcon()}
        </div>
      </div>

      <div className="bg-white/70 rounded-lg p-4">
        <p className="text-slate-700 leading-relaxed">
          {explanation}
        </p>
      </div>

      <div className="mt-4 flex items-center gap-4 text-xs text-slate-500">
        <div className="flex items-center gap-1">
          <div className="w-2 h-2 rounded-full bg-primary-500" />
          <span>LLM-Generated</span>
        </div>
        <div className="flex items-center gap-1">
          <div className="w-2 h-2 rounded-full bg-success" />
          <span>Verified by 5-Layer System</span>
        </div>
      </div>
    </motion.div>
  );
}
